### ISSUE TITLE
eventDate mapping

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/bryophytes-belgium-checklist#3]
For some species, I need an opinion on the interpretation of the dates of first and last observation:

date_from | date_to
--- | ---
absent | 2007
extinct | extinct

With respect to species for which `date_from = absent` I found this information in the paper:
> Fourteen species are reported as new since the 2001 checklist

These species have their `origin` set as cryptogenic. I think `eventDate` for these species should be `2007/2007` as these species were not yet observed in 2001.

For the extinct species (only one, i.e. _Catoscopium nigritum_ (Hedw.) Brid.) , I don't really know what to do. In case of the manual of alien plants, we know that a species was present between a certain time range, and that it has gone extinct after that period. In the case of the Bryophyte checklist, we don't really know between which date range it was present... Maybe leave `eventDate` empty? The `extinct` information should go in invasion stage (for now)

**Comment by peterdesmet** [comment]
I agree with “2017/2017” and leaving the date empty for extinct species. Note that “extinct” could be used as a occurrenceStatus: 
http://rs.gbif.org/vocabulary/gbif/occurrence_status.xm it will be interpreted as “absent”
