### ISSUE TITLE
threatStatus rare

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/bryophytes-belgium-checklist#4]
Information for `threatStatus` can be found in `european_red_list_species`.
This contains the value `rare`. This is not a IUCN Threat Status Vocabulary. 
Suggestions? I guess we could just not map `rare`?

**Comment by peterdesmet** [comment]
Even if not an official term, I would map to `rare`, cf.: https://github.com/inbo/eurobutt-checklist/blob/6c199e56902574d18ed765a836d62fdfd7ab6da5/src/dwc_mapping.Rmd#L390

**Comment by qgroom** [comment]
Agree, this is an expression of the abundance, not the degree of threat.
Some rare things are not threatened.
Quentin

**Comment by LienReyserhove** [comment]
great, let's do that!
